// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-rQz1IsxhZpLZmxH1GV9vOeYNU1fQuzo',
    appId: '1:794448243341:web:d283eff31f7909914fd0c4',
    messagingSenderId: '794448243341',
    projectId: 'myplanner-ef92f',
    authDomain: 'myplanner-ef92f.firebaseapp.com',
    databaseURL: 'https://myplanner-ef92f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myplanner-ef92f.appspot.com',
    measurementId: 'G-39KS1EDVV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoSvzhMtO646I7kvlLtrkOkl-qje_wy2o',
    appId: '1:794448243341:android:7aa77a06bcc993d44fd0c4',
    messagingSenderId: '794448243341',
    projectId: 'myplanner-ef92f',
    databaseURL: 'https://myplanner-ef92f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myplanner-ef92f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWdy141rSn6RIm07R9_NLS2BK5AEYwV94',
    appId: '1:794448243341:ios:05906b149c2bc2c84fd0c4',
    messagingSenderId: '794448243341',
    projectId: 'myplanner-ef92f',
    databaseURL: 'https://myplanner-ef92f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myplanner-ef92f.appspot.com',
    iosClientId: '794448243341-n3kokm6vdp4i8b2g3kcd83359rf3tkkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWdy141rSn6RIm07R9_NLS2BK5AEYwV94',
    appId: '1:794448243341:ios:05906b149c2bc2c84fd0c4',
    messagingSenderId: '794448243341',
    projectId: 'myplanner-ef92f',
    databaseURL: 'https://myplanner-ef92f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myplanner-ef92f.appspot.com',
    iosClientId: '794448243341-n3kokm6vdp4i8b2g3kcd83359rf3tkkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myplanner',
  );
}
